/**
 * The 50 U.S. states used by the constraint graph. The District of Columbia
 * and U.S. territories are intentionally outside the lesson's scope.
 */
export const STATE_CODES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
] as const;

export type StateCode = (typeof STATE_CODES)[number];

export const STATE_NAMES: Readonly<Record<StateCode, string>> = Object.freeze({
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
});

/**
 * Shared land borders only. Point contacts (for example, AZ–CO) and water-only
 * boundaries are excluded. Alaska and Hawaii therefore have no neighbors.
 * Neighbor arrays are alphabetized to make propagation and narration stable.
 */
export const ADJACENCY: Readonly<Record<StateCode, readonly StateCode[]>> =
  Object.freeze({
    AL: Object.freeze(["FL", "GA", "MS", "TN"]),
    AK: Object.freeze([]),
    AZ: Object.freeze(["CA", "NM", "NV", "UT"]),
    AR: Object.freeze(["LA", "MO", "MS", "OK", "TN", "TX"]),
    CA: Object.freeze(["AZ", "NV", "OR"]),
    CO: Object.freeze(["KS", "NE", "NM", "OK", "UT", "WY"]),
    CT: Object.freeze(["MA", "NY", "RI"]),
    DE: Object.freeze(["MD", "NJ", "PA"]),
    FL: Object.freeze(["AL", "GA"]),
    GA: Object.freeze(["AL", "FL", "NC", "SC", "TN"]),
    HI: Object.freeze([]),
    ID: Object.freeze(["MT", "NV", "OR", "UT", "WA", "WY"]),
    IL: Object.freeze(["IA", "IN", "KY", "MO", "WI"]),
    IN: Object.freeze(["IL", "KY", "MI", "OH"]),
    IA: Object.freeze(["IL", "MN", "MO", "NE", "SD", "WI"]),
    KS: Object.freeze(["CO", "MO", "NE", "OK"]),
    KY: Object.freeze(["IL", "IN", "MO", "OH", "TN", "VA", "WV"]),
    LA: Object.freeze(["AR", "MS", "TX"]),
    ME: Object.freeze(["NH"]),
    MD: Object.freeze(["DE", "PA", "VA", "WV"]),
    MA: Object.freeze(["CT", "NH", "NY", "RI", "VT"]),
    MI: Object.freeze(["IN", "OH", "WI"]),
    MN: Object.freeze(["IA", "ND", "SD", "WI"]),
    MS: Object.freeze(["AL", "AR", "LA", "TN"]),
    MO: Object.freeze(["AR", "IA", "IL", "KS", "KY", "NE", "OK", "TN"]),
    MT: Object.freeze(["ID", "ND", "SD", "WY"]),
    NE: Object.freeze(["CO", "IA", "KS", "MO", "SD", "WY"]),
    NV: Object.freeze(["AZ", "CA", "ID", "OR", "UT"]),
    NH: Object.freeze(["MA", "ME", "VT"]),
    NJ: Object.freeze(["DE", "NY", "PA"]),
    NM: Object.freeze(["AZ", "CO", "OK", "TX"]),
    NY: Object.freeze(["CT", "MA", "NJ", "PA", "VT"]),
    NC: Object.freeze(["GA", "SC", "TN", "VA"]),
    ND: Object.freeze(["MN", "MT", "SD"]),
    OH: Object.freeze(["IN", "KY", "MI", "PA", "WV"]),
    OK: Object.freeze(["AR", "CO", "KS", "MO", "NM", "TX"]),
    OR: Object.freeze(["CA", "ID", "NV", "WA"]),
    PA: Object.freeze(["DE", "MD", "NJ", "NY", "OH", "WV"]),
    RI: Object.freeze(["CT", "MA"]),
    SC: Object.freeze(["GA", "NC"]),
    SD: Object.freeze(["IA", "MN", "MT", "ND", "NE", "WY"]),
    TN: Object.freeze(["AL", "AR", "GA", "KY", "MO", "MS", "NC", "VA"]),
    TX: Object.freeze(["AR", "LA", "NM", "OK"]),
    UT: Object.freeze(["AZ", "CO", "ID", "NV", "WY"]),
    VT: Object.freeze(["MA", "NH", "NY"]),
    VA: Object.freeze(["KY", "MD", "NC", "TN", "WV"]),
    WA: Object.freeze(["ID", "OR"]),
    WV: Object.freeze(["KY", "MD", "OH", "PA", "VA"]),
    WI: Object.freeze(["IA", "IL", "MI", "MN"]),
    WY: Object.freeze(["CO", "ID", "MT", "NE", "SD", "UT"]),
  }) as Readonly<Record<StateCode, readonly StateCode[]>>;
